### ISSUE TITLE
Cannot restart OpenAdmin UI from panel

### ISSUE THREAD

**Issue by Seff300** [stefanpejcic/OpenPanel#1015]
### OpenPanel version(s) affected

1.7.64

### What OS are you using?

Ubuntu

### Are you able to reproduce the problem on the demo site https://demo.openpanel.com:2083/ ?

No

### Description

After restarting OpenAdmin UI and then attempting to restart it once more I get the following error:
`Failed to restart service 'admin'. Try from terminal: 'systemctl restart admin'`

`opencli admin log `shows the following errors:
```
Restarting OpenAdmin service:
tail -f 25 /var/log/openpanel/admin/error.log

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen 2087.app>", line 498, in wrapper
  File "<frozen 2087.modules.settings.updates>", line 172, in up_update_settings
  File "/usr/local/admin/venv/lib/python3.12/site-packages/flask/templating.py",                                         line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/admin/venv/lib/python3.12/site-packages/flask/templating.py",                                         line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/admin/venv/lib/python3.12/site-packages/jinja2/environment.py                                        ", line 1295, in render
    self.environment.handle_exception()
  File "/usr/local/admin/venv/lib/python3.12/site-packages/jinja2/environment.py                                        ", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/admin/templates/settings/updates.html", line 1, in top-level                                         template code
    {% extends 'base.html' %}
  File "/usr/local/admin/templates/base.html", line 1017, in top-level template                                         code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/admin/templates/settings/updates.html", line 147, in block 'c                                        ontent'
    <option {%if config_data['PANEL']['autoupdate'] == 'off' and config_data['PA                                        NEL']['autopatch'] == 'on'%}selected{% endif %} value="minor_only">Minor version                                        s only (bug fixes and security patches)</option>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/admin/venv/lib/python3.12/site-packages/jinja2/environment.py                                        ", line 471, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'PANEL'
```

After rebooting the server I'm still unable to restart OpenAdmin UI from the OpenAdmin panel

### How to reproduce

Update to 1.7.64 from 1.7.63 and restart OpenAdmin UI, then wait a bit and try to restart it again.

**Comment by stefanpejcic** [comment]
caused by #1016
